train_input_data_path: "../data/eng/train/eng_train_new.tsv"
dev_input_data_path: "../data/eng/dev/eng_dev_combined.tsv"
dev_gold_path: "../data/eng/dev/goldstandard_dev_2022.tsv"
test_input_data_path: false
vector_type: "bow_only"
classifier: "dt"
output_dir: "../outputs/D2"
predictions_file: "D2_best_system_bow_dt_predictions_neg.tsv"
results_dir: "../results"
score_file: "neg_enhanced_D2_scores.out"
